name: Build and Deploy Slides

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'slides.qmd'
      - 'styles.css'
      - '.github/workflows/build-deploy-slides.yml'

permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pip dependencies
        run: |
          pip install jupyter
          pip install -r requirements.txt

      - name: Render slides to HTML
        run: quarto render slides.qmd --to html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          cname: false
